name = "PointClouds"
uuid = "3cc211ed-1f43-4d33-a894-629186066e97"
authors = ["Manuel F. Schmid <mfs2173@columbia.edu>"]
version = "1.1.0"

[deps]
BaseDirs = "18cc8868-cbac-4acf-b575-c8ff214dc66f"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LASzip_jll = "8372b9c3-1e34-5cc3-bfab-1a98e101de11"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
Proj = "c94c279d-25a6-4763-9509-64d165bea63e"

[compat]
AllocCheck = "0.2.2"
BaseDirs = "1.2"
DataFrames = "1.6"
Dates = "1.10"
HTTP = "1.10"
JSON3 = "1.14"
LASzip_jll = "3.4"
Mmap = "1.10"
NearestNeighbors = "0.4"
Polyester = "0.7"
Proj = "1.7"
Test = "1.10"
julia = "1.10"

[extras]
AllocCheck = "9b6a8646-10ed-4001-bbdc-1d2f46dfbb1a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["AllocCheck", "Test"]
